### ISSUE TITLE
Reloads libraries and packages

### ISSUE THREAD

**Issue by Axiks** [Puzzak/tgcrawl#12]
Each time the program starts, it reloads language packs, TDLib, etc

**Comment by Puzzak** [comment]
It actually loads them anew. Language and configs are made this way so developers can fix typos and add login steps to the app without updating it, and tdlib has to be booted in order to make app work. Unfortunately, this is the correct behavior.

**Comment by Puzzak** [comment]
Closing this as I can't do anything with it. Even Telegram apps do this, they serve you cached data and update it after booting TDLib in background.
